<?xml version="1.0"?>

<!DOCTYPE cyclos-changelog [
    <!-- Root element -->
    <!ELEMENT cyclos-changelog (version+)>

    <!-- Version descriptor -->
    <!ELEMENT version (
        description?, 
        enhancements?, 
        bug-fixes?, 
        new-libraries?, 
        removed-libraries?, 
        new-helps?, 
        removed-helps?, 
        new-static-files?, 
        removed-static-files?,
        new-translation-keys?,
        removed-translation-keys?,
        new-setup-keys?,
        removed-setup-keys?,
        new-css-classes?,
        removed-css-classes?,
        statements*,
        migration*
    )>
    <!ATTLIST version label CDATA #REQUIRED>

    <!-- Optional version description -->
    <!ELEMENT description (#PCDATA)>

    <!-- 
        Database statements to be applied if autoSchemaUpgrade is enabled.
        The required database attribute indicates the database name (same as the returned
        by java.sql.DatabaseMetaData.getDatabaseProductName(), but case insensitive)
        that the statements apply.
    -->
    <!ELEMENT statements (item*)>
    <!ATTLIST statements database CDATA #REQUIRED>

    <!-- 
        A migration class to be executed
    -->
    <!ELEMENT migration EMPTY>
    <!ATTLIST migration database CDATA #REQUIRED>
    <!ATTLIST migration class CDATA #REQUIRED>
    
    <!-- Contains a list of new / modified features -->
    <!ELEMENT enhancements (item*)>

    <!-- Contains a list of bug fixes -->
    <!ELEMENT bug-fixes (item*)>

    <!-- Contains a list of new help files -->
    <!ELEMENT new-helps (item*)>

    <!-- Contains a list of removed help files -->
    <!ELEMENT removed-helps (item*)>

    <!-- Contains a list of new static files -->
    <!ELEMENT new-static-files (item*)>

    <!-- Contains a list of removed static files -->
    <!ELEMENT removed-static-files (item*)>

    <!-- Contains a list of new translation keys -->
    <!ELEMENT new-translation-keys (item*)>

    <!-- Contains a list of removed translation keys -->
    <!ELEMENT removed-translation-keys (item*)>

    <!-- Contains a list of new translation keys on the setup package -->
    <!ELEMENT new-setup-keys (item*)>

    <!-- Contains a list of removed translation keys on the setup package -->
    <!ELEMENT removed-setup-keys (item*)>

    <!-- Contains a list of new CSS classes -->
    <!ELEMENT new-css-classes (item*)>

    <!-- Contains a list of removed CSS classes -->
    <!ELEMENT removed-css-classes (item*)>

    <!-- A list item -->
    <!ELEMENT item (#PCDATA)>
]>

<cyclos-changelog>
	<version label="3.6.1">
		<enhancements>
			<item>Improvements on account fee execution handling: It is now possible to view an specific account fee execution details</item>
			<item>Improved performance when used Hibernate second level cache</item>
			<item>It is now possible to export member records to CSV from the global search</item>
			<item>Added a message for the first execution on standalone, after creating the DB, that Cyclos is still initializing</item>
			<item>Now the variables in notifications have been standardized and documented. Existing notification on the database have been updated to the new value.</item>
			<item>Improved the extension point of defining Java class names which are notified on payments</item>
			<item>Improved the account fee charging handing. Now, no manual administrator intervention is needed, except for starting fees defined to manually run. The cancel and recharge actions were removed.</item>
			<item>On the transaction type details, the transaction fees and broker commissions lists now include a column for the 'enabled' property</item>
			<item>Added a permission to change member e-mail. All groups with permission to change the name should initially have that permission too.</item>
			<item>Added the transaction number to the mobile / wap view payment page</item>
			<item>Added a flag on member group to show the description field on payments performed via PosWeb access</item>
			<item>Improved default layout of the posweb access (if there is an applied theme, you may need to re-apply it)</item>
			<item>Added an option in cyclos.properties to control the creation of a new session cookie right after logging-in. This option is better for security, but caused problems with some versions of Joomla when embedding Cyclos in an IFrame</item>
		</enhancements>

		<bug-fixes>
			<item>If a member doesn't save his preferences he will never receive a sms mailing</item>
			<item>The member's group sms preferences were not taken into account when the sms status is created the first time</item>
			<item>Admins with permission to grant loans but without permission to make regular payments where being denied from granting loans</item>
			<item>Saving a transaction fee or broker commission while setting specific 'to groups' could result in permission denied errors</item>
			<item>Text custom fields which are set for search filters where not correctly being applied</item>
			<item>When customizing a new file, the 'Modify' button shouldn't be displayed</item>
			<item>Payment description was not being returned via web services</item>
			<item>Javascript error on print pages</item>
			<item>Actions in the payment confirmation page (print / go to profile / new payment) where not working on some cases</item>
			<item>After performing a system payment, the buttons on confirmation page didn't work</item>
			<item>Javascript error on edit guarantee type</item>
			<item>If an existing database with pending Lucene index operations in a future date are found, the index would be indefinitely rebuilt</item>
			<item>Under some circumstances, the low units notification was not being sent</item>
			<item>The low units message on the group account settings was never used, when it should override (if present) the body in the message settings</item>
			<item>It was not possible to permanently remove an inactive member if there where member records or remarks</item>
			<item>It was not possible to enable a loan transfer type due to a JavaScript error</item>
			<item>On the account fee executions page, the next execution for daily or weekly scheduled account fees where incorrect</item>
			<item>On the account fees list, on the account type details, for weekly fees, the weekday was not being correctly displayed</item>
			<item>When trying to login with an user of a group without permission to login, an error log was being mistakenly generated</item>
			<item>Removed unused alert setting: Alert new pending members. This setting is no longer used since we added the e-mail validation on registration</item>
			<item>If a member had a blocked transaction password, the admins or broker couldn't change his PIN</item>
			<item>It was not possible for admins to accept invoices in behalf of members if the payment type is disabled (only for generated invoices)</item>
			<item>Fixed a duplicate validation message on public registration indicating that the e-mail is not unique</item>
			<item>Filtering the account history by group filters or groups always resulted in empty list</item>
			<item>On mobile and WAP payments, the description shouldn't be required</item>
			<item>The standalone server was not working with Java 7 on Windows</item>
			<item>E-mails were being required to be unique even if the settings said they shouldn't</item>
			<item>Ugly radio buttons were being generated for custom fields (thanks to timreeves)</item>
			<item>In case of validation error on the account fee page, after showing the error popup window, the error was being shown again in a new page</item>
			<item>Volume account fees with period = 1 day where never being charged</item>
			<item>Removed an unnecessary warning when disabling a volume account fee</item>
			<item>Webshop (external) payments were broken</item>
			<item>Changed the color of the 'no e-mail' text in notification preferences to make it more visible</item>
			<item>On admin group permissions, the transfer types were not being updated on the fly when changing the system accounts visibility</item>
			<item>When making a payment from member to member as admin or broker, after selecting a destination member, the back button would jump to that member profile, instead of the original member's profile</item>
			<item>When an administrator or broker couldn't change a member pin, only the external access, the page was still showing the change pin form</item>
			<item>Sometimes, a message that there were errors while displaying the results was being shown on the error / information page by mistake</item>
			<item>When there where new translation-related settings, the first time the application starts up, it would show them always in English</item>
			<item>An administrator with the permission to view account management, but without permission to view account information for any system accounts always had an error when trying to view the system accounts overview page</item>
			<item>If a scheduled account fee was disabled for a long time and then re-enabled, the next charged period would be wrong, taking the old execution as base</item>
			<item>When a session was expired, the last login date of the user was not updated</item>
			<item>When using fixed numbers on a custom field mask (example: \0\9########), the value was not correctly being saved</item>
			<item>When permanently removing a message through the remove icon, but the checkbox was also checked, there was an error</item>
			<item>Expired advertisements or removed members could be loaded via web services using the load method</item>
			<item>The state report was showing wrong results for system / member account balance when there are chargebacks</item>
			<item>On profile or ad details, enumerated custom fields with parent fields had the first option selected when clicking modify / cancel, instead of the original value again</item>
			<item>Removing HTML tags from fields didn't handle spaces correctly on the output. This caused issues with indexing of HTML custom fields with nested tags</item>
			<item>Stop customizing an application page could lead to the old content being served</item>
			<item>On the login page, when pressing enter while on the login name field, the password field should receive focus</item>
			<item>Custom fields of type date, decimal or boolean, when used as search filters where always causing empty results</item>
			<item>For large number of results in export member records to CSV, an application error could happen</item>
			<item>It was possible to create an advertisement as scheduled with a future publication date, then changing it to permanent, making it appear first in the result list (which is ordered by publication start date)</item>
			<item>Entering invalid username in webshop payment generated an application error (and a new error log entry)</item>
		</bug-fixes>

		<new-libraries>
			<item>hazelcast-1.9.4.8.jar</item>
		</new-libraries>

		<removed-libraries>
			<item>hazelcast-1.9.4.4.jar</item>
		</removed-libraries>

		<new-translation-keys>
			<item>accountFee.noMatchingMembers</item>
			<item>accountFee.title.logDetails</item>
			<item>accountFee.title.memberSearch</item>
			<item>accountFeeLog.acceptedInvoices</item>
			<item>accountFeeLog.count</item>
			<item>accountFeeLog.failedMembers</item>
			<item>accountFeeLog.finishDate</item>
			<item>accountFeeLog.finished</item>
			<item>accountFeeLog.neverRan</item>
			<item>accountFeeLog.openInvoices</item>
			<item>accountFeeLog.payments</item>
			<item>accountFeeLog.period</item>
			<item>accountFeeLog.processedMembers</item>
			<item>accountFeeLog.rechargeFailed</item>
			<item>accountFeeLog.rechargingFailed</item>
			<item>accountFeeLog.running</item>
			<item>accountFeeLog.skippedMembers</item>
			<item>accountFeeLog.status.ACCEPTED_INVOICE</item>
			<item>accountFeeLog.status.ERROR</item>
			<item>accountFeeLog.status.INVOICE</item>
			<item>accountFeeLog.status.OPEN_INVOICE</item>
			<item>accountFeeLog.status.PROCESSED</item>
			<item>accountFeeLog.status.SKIPPED</item>
			<item>accountFeeLog.status.TRANSFER</item>
			<item>accountFeeLog.stillRunning</item>
			<item>accountFeeLog.totalAmount</item>
			<item>accountFeeLog.totalCollectedAmount</item>
			<item>accountFeeLog.totalInvoices</item>
			<item>alert.member.nullIRate</item>
			<item>alert.system.ACCOUNT_FEE_FINISHED_WITH_ERRORS</item>
			<item>alert.system.accountFeeFinishedWithErrors</item>
			<item>alert.system.nullIRate</item>
			<item>group.account.pendingAccounts</item>
			<item>group.settings.showPosWebPaymentDescription</item>
			<item>group.title.settings.payments</item>
			<item>message.error.pendingMessagesToBeSent</item>
			<item>mobile.viewPayments.transactionNumber</item>
			<item>permission.adminMembers.changeEmail</item>
			<item>permission.brokerMembers.changeEmail</item>
			<item>permission.memberProfile.changeEmail</item>
			<item>posweb.bannerText</item>
			<item>smsMailing.byBroker.all</item>
		</new-translation-keys>

		<removed-translation-keys>
			<item>accountFee.action.alreadyFinished</item>
			<item>accountFee.action.cancel.confirmation</item>
			<item>accountFee.action.canceled</item>
			<item>accountFee.action.recharge.confirmation</item>
			<item>accountFee.action.recharged</item>
			<item>accountFee.disableConfirmation</item>
			<item>accountFeeLog.status.CANCELED</item>
			<item>accountFeeLog.status.FINISHED</item>
			<item>accountFeeLog.status.NEVER_RAN</item>
			<item>accountFeeLog.status.PARTIALLY_FAILED</item>
			<item>accountFeeLog.status.RUNNING</item>
			<item>alert.system.ACCOUNT_FEE_CANCELLED</item>
			<item>alert.system.ACCOUNT_FEE_FAILED</item>
			<item>alert.system.ACCOUNT_FEE_RECOVERED</item>
			<item>alert.system.accountFeeCancelled</item>
			<item>alert.system.accountFeeFailed</item>
			<item>alert.system.accountFeeRecovered</item>
			<item>group.account.pendingInitialCredits</item>
			<item>group.title.settings.scheduledPayments</item>
			<item>lastTransaction.commit</item>
			<item>loan.title.canPerformExpiredAction</item>
			<item>permission.adminMemberRemarks</item>
			<item>permission.adminMemberRemarks.manage</item>
			<item>permission.adminMemberRemarks.view</item>
			<item>smsMailing.broker.group</item>
		</removed-translation-keys>

		<new-setup-keys>
			<item>setup.standalone.starting</item>
		</new-setup-keys>
		
        <statements database="mysql">
        	<item>alter table account_fee_logs add column finish_date datetime</item>
        	<item>update account_fee_logs l inner join account_fees f on l.account_fee_id = f.id set l.finish_date = l.date where l.status = 'F' or f.enabled_since is null</item>
        	<item>alter table account_fee_logs drop column status</item>
        	<item>delete from alerts where msg_key in ('alert.system.accountFeeCancelled', 'alert.system.accountFeeFailed', 'alert.system.accountFeeRecovered')</item>
			<item>update settings set value = replace(value, '#fromMemberName#', '#from_member#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#toMemberName#', '#to_member#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#fromMemberUsername#', '#from_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#toMemberUsername#', '#to_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#brokerUsername#', '#broker_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#memberUsername#', '#member_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#grantDate#', '#grant_date#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#issuerName#', '#issuer_member#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#issuerUsername#', '#issuer_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#buyerName#', '#buyer_member#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#buyerUsername#', '#buyer_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#sellerName#', '#seller_member#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#sellerUsername#', '#seller_login#') where type = 'message'</item>
			<item>update settings set value = replace(value, '#creditLimit#', '#credit_limit#') where type = 'message'</item>
			<item>alter table accounts add column last_low_units_sent datetime</item>
			<item>alter table account_fee_logs add unique key uk_fee_log_fee_date (account_fee_id, date)</item>
			<item>delete from settings where name='alertNewPendingMembers'</item>
			<item>insert into permissions (group_id, permission) select group_id, 'AdminMemberPermission.MEMBERS_CHANGE_EMAIL' from permissions where permission = 'AdminMemberPermission.MEMBERS_CHANGE_NAME'</item>
			<item>insert into permissions (group_id, permission) select group_id, 'BrokerPermission.MEMBERS_CHANGE_EMAIL' from permissions where permission = 'BrokerPermission.MEMBERS_CHANGE_NAME'</item>
			<item>insert into permissions (group_id, permission) select group_id, 'MemberPermission.PROFILE_CHANGE_EMAIL' from permissions where permission = 'MemberPermission.PROFILE_CHANGE_NAME'</item>
			<item>alter table member_account_fee_logs add column amount decimal(15,6), add column success bit(1) not null default false</item>
			<item>update member_account_fee_logs l inner join invoices i on l.invoice_id = i.id set l.amount = i.amount</item>
			<item>update member_account_fee_logs l inner join transfers t on l.transfer_id = t.id set l.amount = t.amount</item>
			<item>update member_account_fee_logs set amount = 0 where transfer_id is null and invoice_id is null</item>
			<item>update member_account_fee_logs set success = true</item>
			<item>alter table account_fee_logs add column recharging_failed bit(1) not null default false</item>
			<item>create table members_pending_charge (member_id integer not null, account_fee_log_id integer not null) ENGINE=InnoDB</item>
			<item>alter table members_pending_charge add index FK265D1E42EAE0AB57 (member_id), add constraint FK265D1E42EAE0AB57 foreign key (member_id) references members (id)</item>
			<item>alter table members_pending_charge add index FK265D1E426957A5AA (account_fee_log_id), add constraint FK265D1E426957A5AA foreign key (account_fee_log_id) references account_fee_logs (id)</item>
			<item>
				insert into members_pending_charge 
				(account_fee_log_id, member_id) 
				select l.id, m.id 
				from account_fee_logs l cross join members m
				where m.subclass = 'M'
				and l.finish_date is null 
				and m.group_id in (
					select gaf.group_id
					from groups_account_fees gaf
					where gaf.account_fee_id = l.account_fee_id
				)
				and not exists (
					select 1
					from member_account_fee_logs ml
					where ml.account_fee_log_id = l.id
					  and ml.member_id = m.id
				)
			</item>
			<item>alter table account_fee_logs add column total_members integer</item>
			<item>
				update account_fee_logs l 
				set l.total_members = (
						select count(*) as count
						from member_account_fee_logs mafl
						where mafl.account_fee_log_id = l.id
					) + (
						select count(*) as count
						from members_pending_charge mpc
						where mpc.account_fee_log_id = l.id
					)
				where l.total_members is null
			</item>
			<item>alter table account_fee_logs add column failed_members integer not null default 0</item>
			<item>alter table account_fee_logs add column recharge_attempt integer not null default 0</item>
			<item>alter table member_account_fee_logs add column recharge_attempt integer not null default 0</item>
			<item>alter table groups add column member_show_posweb_pmt_dsc bit(1) not null default false</item>
			<item>
				insert into alerts (subclass, date, removed, member_id, msg_key, arg0) 
				select 'M', current_timestamp(), false, m.id, 'alert.member.initialCreditFailed', at.name
				from pending_initial_credits pic 
					inner join accounts a on pic.account_id = a.id
					inner join account_types at on a.type_id = at.id
					inner join members m on a.member_id = m.id
			</item>
			<item>drop table pending_initial_credits</item>
			<item>update ads set publication_start = creation_date where permanent = true</item>
        </statements>
	</version>
	
    <version label="3.6">
        <enhancements>
        	<item>Improved HTML / JavaScript performance and standards compliance</item>
        	<item>On the login form, pressing enter will focus the next field, or submit the form if on password field</item>
		</enhancements>
		
		<bug-fixes>
			<item>Members couldn't see their operators. After the first member listed his operators / groups, other members wouldn't be able to see their own operators</item>
			<item>When an installment of a scheduled payment when authorization is needed is authorized, it means now that on due dates, the next installments won't go through the authorization process again</item>
			<item>When exporting members or advertisements as CSV, the last record was not being included on the file</item>
			<item>Scheduled payments from system to member would result in a permission error if the receiver member would try to view the payment details</item>
			<item>It was not possible to save transaction fees</item>
			<item>When using a customized login page for group / group filter, clicking on access options would show the global login page</item>
			<item>Now the error page during posweb has the posweb header and footer (if customized, as they are empty by default)</item>
			<item>There were no confirmation messages for info texts being inserted or modified</item>
			<item>Operators without permissions to view his member's account couldn't do receive payments on WebPOS. Also, without the regular make payment permission, the WebPOS make payment permission was not enough</item>
			<item>When an account fee was disabled, then re-enabled in a future date, the next execution was being based on the last execution, not on the new enabling date</item>
			<item>Administrator notifications from payments made through external channels were not being sent</item>
			<item>When editing an existing customized file, after clicking change and then cancel, the contents were cleared</item>
			<item>A permission denied exception was thrown when chargeback a payment to system</item>			
		</bug-fixes>

		<new-libraries>
			<item>json_simple-1.1.jar</item>
		</new-libraries>
				
		<new-translation-keys>
            <item>createMember.created</item>
            <item>createMember.created.mailError</item>
            <item>settings.local.language.GREEK</item>
		</new-translation-keys>
		
		<removed-translation-keys>
		            <item>createMember.admin.created</item>
		            <item>createMember.admin.created.mailError</item>
		            <item>createMember.broker.created</item>
		            <item>createMember.broker.created.mailError</item>
		            <item>settings.local.language.Greek</item>
		</removed-translation-keys>
		
		<statements database="mysql">
			<item>insert into settings(type, name, value) 
					select distinct 'local', 'smsEnabled', 'true' 
					from settings s 
					where not exists (select id from settings where type='local' and name = 'smsEnabled') 
	  				and exists (select id from settings where type='local' and name = 'sendSmsWebServiceUrl' and value is not null) 
	  				and exists (select id from settings where type='local' and name = 'smsChannelName' and value is not null) 
	  				and exists (select id from settings where type='local' and name = 'smsCustomFieldId' and value is not null)</item>
        </statements>
	</version>
	
    <version label="3.6_RC2">
        <enhancements>
        	<item>General auditing and review on security. Cyclos should be much more secure now</item>
        	<item>Faster startup times</item>
        	<item>Lots of performance improvements</item>
        	<item>It is now possible to deploy Cyclos in a cluster, allowing not only high availability, but better scalability</item>
        	<item>It is now possible to choose whether to log to trace file only if there were database writes</item>
        	<item>Now logging generated from web service access goes to a separate file</item>
        	<item>Added an access setting to allow or not concurrent logins from the same user</item>
			<item>Support was added to allow a WS client to set a trace data that will be transferred to the external WS implementors. For example: trace data attached to a payment done by WS will be transferred to the receiver through the corresponding notification generated from that payment</item>
        	<item>Added the possibility to use a local receipt printer on PosWeb and in the main web interface for printing transaction receipts (a permission should be granted first)</item>
        	<item>Processed payment requests can now be printed directly on the request payment page</item>
        	<item>Now operators can filter the account history by operator, just like the member</item>
        	<item>Payments generated through accepted invoices which were sent by operators can now be queried on the account history through the operator filter</item>
        	<item>Added a blacklist and a whitelist for groups allowed to login in cyclos.properties</item>
        	<item>Added 2 extra options for transaction fees as payer or receiver: source member broker and destination member broker</item>
        	<item>Added to member group the default options for SMS notifications (allow charging, accept free mailings and accept paid mailings)</item>
        	<item>When no card types or registration agreements, those no longer appear on group details page</item>
        	<item>It is now possible to have ad interests only with title and type</item>
        	<item>When there are pending commission contracts, the member home shows a link now</item>
        	<item>The admin e-mail notification for new registered members has been extended not only to public registration, but now allows any member group and any type of registration</item>
        	<item>On broker's registered members list the status filter for 'Awaiting activation' now only shows up if the broker's group has inactive groups as possible initial groups for registration</item>
        	<item>Broker commissions paid by members now only allows the corresponding broker in relation to the member paying the commission (either source or destination). Previous versions allowed a quite strange combination of one member paying to the other one's broker, which conflicted with commission contracts and default commission settings</item>
        	<item>Now it's possible to have a catalog with the SMS operations. This will allow, for example, add custom commands to the SMS module and set the corresponding message showed in the SMS log</item>
        	<item>The state overview report now supports a date / time for historical data. However, this is not available for invoices, loans and references, as historical data is not stored</item>
        	<item>Added a class name for callbacks on processed transactions in both transfer type (for specific transactions) and in local settings (for all transactions)</item>
        	<item>Now there is a checkbox in the payment custom field to enable / disable it for new payments. It is not possible to remove custom fields once they are used</item>
        	<item>Association or deactivation of new accounts now runs in background.</item> 
        </enhancements>
        
        <bug-fixes>
        	<item>When inserting advertisement categories, the newly created category's order was not at the end of the list</item>
        	<item>When mixing scheduled payments which reserve the total amount with authorized payments, amount reservations were not being correctly returned</item>
        	<item>On posweb access, if the user had an expired password, he/she'd not be forced to change</item>
        	<item>On posweb access, if the member had a pending registration agreement, he/she'd not be forced to accept it</item>
        	<item>Limited system accounts with credit limit greater than zero were not honoring the limit</item>
        	<item>The form for new static document and edit member document didn't work on Google Chrome</item>
        	<item>Removing images didn't remove them from disk cache on the server</item>
        	<item>It was not being validated that a payment cannot be performed if there are pending commission contracts</item>
        	<item>On database creation groups with associated accounts were not set active</item>
        	<item>On the edit transfer type page, scheduled payment settings shouldn't be displayed for loans</item>
        	<item>Customized files which are no longer used will be automatically removed from database on next startup</item>
        	<item>On the account fees log file, when a fee is finished, the log was being generated as if it were starting</item>
        </bug-fixes>
        
		<new-libraries>
			<item>FastInfoset-1.2.9.jar</item>
			<item>antlr-2.7.7.jar</item>
			<item>cxf-2.4.4.jar</item>
			<item>ehcache-core-2.4.6.jar</item>
			<item>hazelcast-1.9.4.4.jar</item>
			<item>hibernate-3.6.8.jar</item>
			<item>hibernate-jpa-2.0-api-1.0.1.Final.jar</item>
			<item>lucene-analyzers-3.4.0.jar</item>